### PR TITLE
AMQNET-572 - Fix for NMS failover/TLS bug, by saving an Ssl context

### PR DESCRIPTION
**Pull request by michaelandrepearce**
Note this is simply a sort out of the PR https://github.com/apache/activemq-nms-openwire/pull/3/files

### CODE REVIEW

**Comment by michaelandrepearce** [comment]
@brudo - i tried to tidy up the original PR so it can be merged.
@lukeabsent - please also have a quick look, as per other PR, its been established the original solution is fine using thread static as the reconnect runs on single thread.

**Comment by michaelandrepearce** [comment]
original dated pr is here: https://github.com/apache/activemq-nms-openwire/pull/3

**Comment by brudo** [comment]
Cross posting... I looked, and it seems to be fine - essentially the same code as we have here, and the only downside I see is that @dtaflin no longer appears in the commit history. I did manage to preserve authorship in a commit my fork, here - brudo/activemq-nms-openwire@c60e83a - but I wasn't sure whether to submit that as a PR or not. Now, I think it would be redundant to add a third active PR on the same issue.

**Comment by michaelandrepearce** [comment]
@brudo if youve managed to keep authorship thats actually better send a pr and well merge that one. I basically only did this quick because it seemed to go dormant

**Comment by michaelandrepearce** [comment]
@brudo i took your branch made a pr https://github.com/apache/activemq-nms-openwire/pull/16 and merged it. Much better to keep original author so thanks for that.

**Pull request closed without merging**
